default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV['BOXEN_POSTGRESQL_PORT'] || 5432 %>
  host: localhost

development:
  <<: *default
  database: resciencec_development

test:
  <<: *default
  database: resciencec_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
