# Changing this file necessitates a server restart
name: "ReScience C"
abbreviation: "ReScienceC"
issn: "2430-3658"
tagline: "Reproducible Science is good. Replicated Science is better."
logo_url: "/logo_large.jpg"
url: "https://resciencec.theoj.org"
editor_email: "editor@resciencec.theoj.org"
noreply_email: "admin@theoj.org"
launch_date: "2016-05-05"
twitter: "@ReScienceEds"
mastodon_url: "https://fosstodon.org/@RescienceC"
google_analytics: ""
github: "ReScience/ReScienceC"
reviews: "ReScience/ReScienceC-reviews"
papers_repo: "ReScience/ReScienceC-papers"
papers_html_url: "https://rescience.github.io/ReScienceC-papers"
reviewers_url: ""
reviewers_signup_url: "https://github.com/ReScience/ReScience/issues/27"
reviewers_lookup_url: "http://resciencec.theoj.org/about#reviewers"
product: "paper" # the *thing* being submitted for review
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the ReScience C submission criteria.
paper_types: []
bot_username: editorialbot
features:
  tracks: true
