# Changing this file necessitates a server restart
name: "ReScience C"
abbreviation: "ReScienceC"
issn: "2430-3658"
tagline: "Reproducible Science is good. Replicated Science is better."
logo_url: "/logo_large.jpg"
url: "http://0.0.0.0:3000"
editor_email: "admin@resciencec.theoj.org"
noreply_email: "noreply@resciencec.theoj.org"
twitter: "@ReScienceEds"
mastodon_url: "https://fosstodon.org/@RescienceC"
google_analytics: ""
github: "ReScience/ReScienceC"
reviews: "aliadalabs/resciencec-reviews-testing"
papers_repo: "aliadalabs/resciencec-papers-testing"
papers_html_url: "https://resciencec.theoj.org"
reviewers_signup_url: "https://github.com/ReScience/ReScience/issues/27"
product: "software" # the *thing* being submitted for review
reviewers: "http://rescience.github.io/board/#reviewers"
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the ReScience C submission criteria.
paper_types: []
bot_username: botsci
